### ISSUE TITLE
Zhong process is stucked

### ISSUE THREAD

**Issue by lefty313** [nickelser/zhong#13] opened 2017-04-11 11:58 UTC
zhong.rb: https://gist.github.com/lefty313/ac57df1dfd97133c9672c8f9f0e77540

Most of my zhong jobs are spawning sidekiq background process, it works fine since months 

![screen shot 2017-04-11 at 13 52 38](https://cloud.githubusercontent.com/assets/686684/24907857/36391682-1ebe-11e7-828d-b06d443f8eaf.png)

as you see single job is schedule once per minute

recently I added following non sidekiq job to my zhong configuration

```ruby
    every 15.seconds, "check access matches" do
      min5   = $redis.zcount("matches:accessed", 5.minutes.ago.to_i, "+inf")
      min25  = $redis.zcount("matches:accessed", 25.minutes.ago.to_i, "+inf")
      hour1  = $redis.zcount("matches:accessed", 1.hour.ago.to_i, "+inf")
      hour24 = $redis.zcount("matches:accessed", 24.hour.ago.to_i, "+inf")
      week   = $redis.zcount("matches:accessed", 7.days.ago.to_i, "+inf")
      total  = $redis.zcount("matches:accessed", "-inf", "+inf")

      NewRelic::Agent.record_metric("Database/MatchAccess/Last5Min", min5)
      NewRelic::Agent.record_metric("Database/MatchAccess/Last25Min", min25)
      NewRelic::Agent.record_metric("Database/MatchAccess/LastHour", hour1)
      NewRelic::Agent.record_metric("Database/MatchAccess/LastDay", hour24)
      NewRelic::Agent.record_metric("Database/MatchAccess/LastWeek", week)
      NewRelic::Agent.record_metric("Database/MatchAccess/Alltime", total)
    end
```

![screen shot 2017-04-11 at 13 51 55](https://cloud.githubusercontent.com/assets/686684/24907889/5b9cc9b4-1ebe-11e7-8d9a-14e478b8f00a.png)

![screen shot 2017-04-11 at 13 58 58](https://cloud.githubusercontent.com/assets/686684/24908082/0ce62490-1ebf-11e7-9cfe-80769dbb2ae2.png)

as you see it's not reporting at time to time. I can fix it by calling 

```ruby
$redis.del($redis.keys("zhong*"))
```

but than it will lock after few minutes again. During lock phase zhong is still working fine for other jobs. 

Am I doing something wrong here ? 

ps: I have autoscalling policy on my production server so one of my servers could be killed when zhong is working.  Keep in mind that zhong is running on every single instance and there is always at least one

**Comment by nickelser** [comment] 2017-04-11 17:52
@lefty313 doesn't look like you are doing anything wrong -- out of curiousity, are you using the same redis for sidekiq and zhong (and here, for `$redis`)?

do you have any logs/exceptions that might be relevant?

**Comment by nickelser** [comment] 2017-07-28 16:08
closing this since I cannot reproduce -- please let me know if you have some steps to reproduce!

**Closed by nickelser** 2017-07-28 16:08 UTC
